CREATE TABLE IF NOT EXISTS movie
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(100),
	sf_url VARCHAR(255),
	imdb_url VARCHAR(255),
	premier_date VARCHAR(50) DEFAULT '',
	age_limit VARCHAR(100) DEFAULT '',
	updated_datetime DATETIME NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (sf_url)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS cinema
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(100),
	city VARCHAR(100)
	updated_datetime DATETIME NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (city, name)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS screening
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	screening_time DATETIME NOT NULL,
	movie_id INT UNSIGNED NOT NULL,
	cinema_id INT UNSIGNED NOT NULL,
	places_left INT UNSIGNED NOT NULL,
	updated_datetime DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (cinema_id) REFERENCES cinema (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY (movie_id) REFERENCES movie (id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
) ENGINE = InnoDB;


/* TODO: Add metadata for movie */